### ISSUE TITLE
What's the default tag that start script is using?

### ISSUE THREAD

**Issue by WillemJiang** [syndesisio/syndesis-quickstarts#20]
It's great that we can start the syndesis from the minishift with the start script. But it takes me few hours to figure out with version of syndesis can work as the default version doesn't point to the latest stable release. 

Is there any tag strategy  that we can use in the start script, such as LATEST, STABLE? 

I think it could save lots of time for the newbee to try out this great project.

**Comment by KurtStam** [comment]
@WillemJiang Hi, the script deploys the latest images from Syndesis (bleeding edge) always. I can add this info to the Quickstart info. Would that have saved you some more time? 

We have a nice tool called `syndesis` ([cmdline](https://doc.syndesis.io/#syndesis-build)) you can use to run a build yourself. So this will allow you to build from a tag if that's what you want. Also Syndesis has productized releases as part of the [RH Fuse project](https://developers.redhat.com/products/fuse/download?sc_cid=701f2000000Rm4GAAS&gclid=EAIaIQobChMIgaq_-cu44QIVkVmGCh1Rcw2_EAAYASAAEgJMIPD_BwE&gclsrc=aw.ds).

BTW thanks for the kind words about our project, and for giving us some feedback.

**Comment by WillemJiang** [comment]
@KurtStam  I'm sorry I missed your last response, I just took a quick look at the README and find out there is only one example of Install Syndesis, maybe we could add more information about how to install different version of syndesis images by using the --tag operator, and we can find the release information from [here](https://github.com/syndesisio/syndesis/releases)

**Comment by KurtStam** [comment]
@WillemJiang also see https://doc.syndesis.io/#syndesis-minishift, the command would be

syndesis minishift --tag <version> --full-reset --install

I think in general we should have more examples on how to use this syndesis command. Let me find a good place to add them. Thanks for the suggestion.
