### ISSUE TITLE
DB-2-DB quickstart needs update

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis-quickstarts#22]
`SELECT * FROM contact` returns collection of data. Because of that, the DB-2-DB quickstart needs to add 'split' step to the integration. 

In my POV, the video should be updated. Because when the user goes only through video, they can overlook that first step returns collection. After deploying, they can see valid error:
```
io.atlasmap.api.AtlasException: Errors: [It's not yet supported to have a collection field as a part of multiple source fields in a same mapping: docId='-LYkO4Do5RqQylyKtUqR', path='/<>/first_name'],
```

Exported integration should be updated too because it is not imported correctly to the actual version of Syndesis. Aggregate step shouldn't be there.
![image](https://user-images.githubusercontent.com/16251792/52846949-3976d080-310b-11e9-9162-7102582e4d87.png)

**Comment by KurtStam** [comment]
Thanks!
