### ISSUE TITLE
Public API demo needs to be updated to use the new UI in 7.4

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis-quickstarts#27]
UI has changed around how environments are created and managed. The demo needs to be updated to show how to create/remove and edit environments using the new CI/CD page.

**Comment by KurtStam** [comment]
Hey @dhirajsb are you volunteering to create a nice new QS showing CI/CD stuff?

**Comment by dhirajsb** [comment]
@KurtStam yes, I will update the demo now that I have finished refactoring the backend in the last sprint.

**Comment by KurtStam** [comment]
Hi @dhirajsb will this be resolved for this 'sprint' 1.8? I'd like to create a tag today or tomorrow.

**Comment by dhirajsb** [comment]
I'm hoping to resolve it later today.
