### ISSUE TITLE
Non-standart Authentication in TODO App

### ISSUE THREAD

**Issue by yelizariev** [syndesisio/syndesis-quickstarts#31]
There is an [Authentication section](https://github.com/syndesisio/syndesis-quickstarts/blob/cfe7429/db-2-api-connector/todo-api.json#L175-L179) In ``db-2-api-connector`` example:
```

  "securityDefinitions": {
    "username_password": {
      "type": "basic"
    }
  },
```

The problem is that swagger 2.0 doesn't have such time of authentication: https://swagger.io/docs/specification/2-0/authentication/

Is it kind of unspecified feature of syndesis?

**Comment by zregvart** [comment]
@yelizariev I think you're considering the significance of `"username_password"` key in that security definition. This has no significance in Syndesis or in OpenAPI, it's an [arbitrary name](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#securityDefinitionsObject) given to a specific security definition, later this definition can be used to specify security requirements for operations.

This is well within the OpenAPI 2.0 specification. Can you elaborate your concern?

**Comment by yelizariev** [comment]
Indeed, ``username_password`` is an arbitrary name. Let's continue in https://github.com/syndesisio/syndesis/issues/4218 then
