### ISSUE TITLE
Importing hello world example leads to warnings

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-quickstarts#35]
![image](https://user-images.githubusercontent.com/1105127/63868047-2b591500-c9b6-11e9-922e-8fe75c817d41.png)

going to "edit integration" and then configure the timer component then saving is fixing th eproblem.

Fuse online version 1.7.13.fuse-740001-redhat-00002

**Comment by KurtStam** [comment]
I've updated. Please reopen if it's still an issue. Thx --Kurt
