### ISSUE TITLE
All flows return 501 not implemented in the export .zip

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-quickstarts#4]
I suspect maybe they should be set to 200 OK?

To do this click on the return path icon at the end of the flow and change the return code, click "Done" and then click "Save as draft" or if you're on the latest Syndesis master clicking on the "Go to operations list" super sekretly saves the integration for you, then I guess it's just a matter of re-exporting.

**Comment by gashcrumb** [comment]
Otherwise right after importing the sample .zip the detail page shows 0 flows implemented.

**Comment by KurtStam** [comment]
@gashcrumb I will redo the video one more time in a week or so when some issues I ran into are resolved. I already recreated a new export, so hopefully you should see 3 flows now.

**Comment by KurtStam** [comment]
updated the API Provider QS.
